language: python
os:
  - linux
  - osx
python:
  - "3.2"
  - "3.3"
  - "3.4"
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "sudo apt-get install git-svn"
script: "./tests.sh"
